export const Errors = {
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  MISSING_PARAMETER: 'MISSING_PARAMETER',
  AUTH: 'AUTH',
  INVALID_TICKET: 'INVALID_TICKET',
  AGE_RESTRICTION: 'AGE_RESTRICTION',
};
